modLoader="javafml"
loaderVersion="[46,)"
license="CC BY-NC-ND 4.0"
showAsResourcePack=false

[[mods]]
modId="wool_collection"
version="${version}"
displayName="The Wool Collection"
displayURL="https://www.curseforge.com/minecraft/mc-mods/wool-collection"
#logoFile="examplemod.png"
#credits=""
authors="Buecher_wurm"
description='''Adds wool variants for various blocks, like fences, stairs, gates, buttons and more!'''

[[dependencies.wool_collection]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.wool_collection]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.4,1.21)"
    ordering="NONE"
    side="BOTH"
