modLoader="javafml"
loaderVersion="[41,)"
license="CC BY-NC-ND 4.0"
showAsResourcePack=false

[[mods]]
modId="wool_collection"
version="${version}"
displayName="The Wool Collection"
displayURL="https://www.curseforge.com/minecraft/mc-mods/wool-collection"
#logoFile="examplemod.png"
#credits=""
authors="Buecher_wurm"
description='''Adds wool variants for various blocks, like fences, stairs, gates, buttons and more!'''

[[dependencies.wool_collection]]
modId="forge"
mandatory=true
versionRange="[41.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.wool_collection]]
modId="minecraft"
mandatory=true
versionRange="[1.19,1.19.3)"
ordering="NONE"
side="BOTH"
