# Project
group=com.tristankechlo.wool_collection

# Common
java_version=16
minecraft_version=1.17.1
version_range=[1.17.1,1.18)

# Forge
forge_version=37.1.1
forge_loader_range=[37,)

# Fabric
fabric_version=0.46.1+1.17
fabric_loader_min=0.14
fabric_loader_version=0.16.5
fabric_range_min_inclusive=1.17.1
fabric_range_max_exclusive=1.18

# Mod options
mod_name=TheWoolCollection
mod_author=Buecher_wurm
mod_id=woolcollection
mod_version=1.1

# Other options
modmenu_version=2.0.17
jei_version=8.3.1.1002

# Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
fabric.loom.multiProjectOptimisation=true
