plugins {
    id 'multiloader-common'
    id 'org.spongepowered.gradle.vanilla' version '0.2.1-SNAPSHOT'
}

minecraft {
    version(minecraft_version)
}

sourceSets.main.resources.srcDir 'src/generated/resources'

dependencies {
    //compileOnly group: 'org.spongepowered', name: 'mixin', version: '0.8.5'
    compileOnly group: 'mezz.jei', name: "jei-${minecraft_version}-common-api", version: "${jei_version}"
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.files
    commonResources sourceSets.main.resources.sourceDirectories.files
}

task generateRessources(type: Exec) {
    outputs.upToDateWhen { false }
    workingDir = file("../generator")
    commandLine = ["python.exe", "generate.py"]
}

configure(generateRessources) {
    group = "build"
    description = "generate all wool variants"
}

// add custom ressource generation task to build task
tasks.build.dependsOn(generateRessources)
